/**
 * The 22 Gyeongsangbuk-do 시/군 that make up the province's National Assembly
 * constituencies, plus the province-wide entry used for 비례대표.
 *
 * Boundaries, centroids, and bounding boxes come from the national dataset
 * (통계청 SGIS 시군구 경계, WGS84) and are regenerated by
 * `scripts/build-gyeongbuk-districts.mjs`. Nothing here is hand-authored, so
 * every coordinate is a real surveyed position rather than an approximation.
 */

import dataset from "./data/gyeongbuk-districts.json";
import {
  type Bbox,
  bboxContains,
  bboxForRegion,
  mercatorToLat,
  mercatorToLon,
  mercatorX,
  mercatorY,
  type RegionBox,
  regionForBbox,
} from "./geo";

export type DistrictKind = "si" | "gun";

export interface District {
  /** 행정표준코드 (5-digit 시군구 code). */
  code: string;
  /** Korean name, e.g. "포항시". */
  name: string;
  /** Romanized name, e.g. "Pohang-si". */
  nameEn: string;
  kind: DistrictKind;
  /** Area-weighted centroid of the main body, [lon, lat]. */
  center: readonly [number, number];
  /** [west, south, east, north] of the main body, in degrees. */
  bbox: Bbox;
  /**
   * Every ring, islets included. This is what decides how much terrain to
   * load: Dokdo is Ulleung-gun and belongs on the map, even though framing
   * the county on it would reduce Ulleungdo to a speck.
   */
  fullBbox: Bbox;
}

interface DistrictRecord {
  code: string;
  name: string;
  nameEn: string;
  kind: string;
  center: number[];
  bbox: number[];
  fullBbox?: number[];
}

/** Sentinel code for 비례대표: no constituency, so the whole province. */
export const PROVINCE_CODE = "47000";

export const DISTRICTS: readonly District[] = (
  dataset.districts as DistrictRecord[]
).map((record) => ({
  code: record.code,
  name: record.name,
  nameEn: record.nameEn,
  kind: record.kind === "si" ? "si" : "gun",
  center: [record.center[0] ?? 0, record.center[1] ?? 0] as const,
  bbox: [
    record.bbox[0] ?? 0,
    record.bbox[1] ?? 0,
    record.bbox[2] ?? 0,
    record.bbox[3] ?? 0,
  ] as const,
  fullBbox: [
    record.fullBbox?.[0] ?? record.bbox[0] ?? 0,
    record.fullBbox?.[1] ?? record.bbox[1] ?? 0,
    record.fullBbox?.[2] ?? record.bbox[2] ?? 0,
    record.fullBbox?.[3] ?? record.bbox[3] ?? 0,
  ] as const,
}));

/** Mainland Gyeongbuk: every 시/군 except the offshore 울릉군. */
export const PROVINCE_BBOX: Bbox = [
  dataset.provinceBbox[0] ?? 0,
  dataset.provinceBbox[1] ?? 0,
  dataset.provinceBbox[2] ?? 0,
  dataset.provinceBbox[3] ?? 0,
];

/**
 * Default terrain region: the whole of mainland Gyeongsangbuk-do, from
 * Sangju/Gimcheon in the west to the Uljin and Pohang coastline, and from
 * Bonghwa in the north to Gyeongju and Cheongdo in the south.
 */
export const PROVINCE_REGION: RegionBox = regionForBbox(PROVINCE_BBOX);

/**
 * How much wider than the province the terrain has to be so a wide console
 * viewport is covered while the whole province is still framed. The terrain
 * is a square, so a 16:9 window would otherwise either crop Gyeongbuk
 * top-to-bottom or show void left and right — this trades a coarser basemap
 * for having real ground under every district edge.
 *
 * Capped so an ultrawide window cannot balloon the tile fetch; past the cap
 * the camera's cover clamp crops instead of leaving void.
 */
const MAX_ASPECT_MARGIN = 2.5;

/**
 * Province region sized for a viewport of the given aspect ratio. At 1:1 this
 * is {@link PROVINCE_REGION}; wider viewports get a proportionally wider
 * square so no district runs off the edge of the loaded data.
 */
export function provinceRegionForAspect(aspect: number): RegionBox {
  const safe = Number.isFinite(aspect) && aspect > 0 ? aspect : 1;
  return regionForBbox(
    PROVINCE_BBOX,
    1.06 * Math.min(Math.max(safe, 1), MAX_ASPECT_MARGIN),
  );
}

export const DATA_SOURCE = dataset.source;

const BY_CODE = new Map(DISTRICTS.map((district) => [district.code, district]));

export function districtByCode(code: string): District | undefined {
  return BY_CODE.get(code);
}

/** Georeference of the loaded terrain, as reported in `map:ready`. */
export interface GeoBounds {
  west: number;
  east: number;
  north: number;
  south: number;
}

/**
 * Convert a real coordinate to the renderer's normalized map point. The
 * terrain grid is linear in Mercator space, so latitude has to be projected
 * before it is interpolated — treating it as linear in degrees drifts by
 * hundreds of metres at province scale.
 */
export function latLonToMapPoint(
  lat: number,
  lon: number,
  bounds: GeoBounds,
): { x: number; y: number } {
  const x0 = mercatorX(bounds.west);
  const x1 = mercatorX(bounds.east);
  const y0 = mercatorY(bounds.north);
  const y1 = mercatorY(bounds.south);
  return {
    x: (mercatorX(lon) - x0) / (x1 - x0),
    y: (mercatorY(lat) - y0) / (y1 - y0),
  };
}

/** Inverse of {@link latLonToMapPoint}. */
export function mapPointToLatLon(
  x: number,
  y: number,
  bounds: GeoBounds,
): { lat: number; lon: number } {
  const x0 = mercatorX(bounds.west);
  const x1 = mercatorX(bounds.east);
  const y0 = mercatorY(bounds.north);
  const y1 = mercatorY(bounds.south);
  return {
    lon: mercatorToLon(x0 + x * (x1 - x0)),
    lat: mercatorToLat(y0 + y * (y1 - y0)),
  };
}

/** Ground width and height of a bbox in meters, at its own latitude. */
export function bboxSpanMeters(bbox: Bbox): { width: number; height: number } {
  const [west, south, east, north] = bbox;
  const midLat = (south + north) / 2;
  const metersPerDegree = 111320;
  return {
    width: (east - west) * metersPerDegree * Math.cos((midLat * Math.PI) / 180),
    height: (north - south) * 110574,
  };
}

/**
 * Where the camera should sit to frame a district: its centroid, and a
 * distance that fits the district's real extent in the 40° vertical FOV with
 * a little margin around it.
 */
export function cameraForBbox(
  bbox: Bbox,
  fovDegrees = 40,
  fill = 0.78,
): { lat: number; lon: number; distanceMeters: number } {
  const { width, height } = bboxSpanMeters(bbox);
  const halfFov = ((fovDegrees / 2) * Math.PI) / 180;
  return {
    lon: (bbox[0] + bbox[2]) / 2,
    lat: (bbox[1] + bbox[3]) / 2,
    distanceMeters: Math.max(width, height) / 2 / Math.tan(halfFov) / fill,
  };
}

/**
 * The terrain region a district needs. Mainland districts reuse the loaded
 * province region so focusing one is just a camera move; 울릉군 sits ~190 km
 * offshore and gets its own region, which forces a terrain reload.
 */
export function regionForDistrict(
  district: District,
  current: RegionBox = PROVINCE_REGION,
): { region: RegionBox; reload: boolean } {
  // Measured against every ring, so a district's outlying islands are inside
  // the loaded terrain rather than off the edge of it.
  if (bboxContains(bboxForRegion(current), district.fullBbox)) {
    return { region: current, reload: false };
  }
  const span = Math.max(
    district.fullBbox[2] - district.fullBbox[0],
    district.fullBbox[3] - district.fullBbox[1],
  );
  // A compact district needs padding to sit in; one that already spans a
  // hundred kilometres of sea does not.
  return {
    region: regionForBbox(district.fullBbox, span > 0.3 ? 1.15 : 3.2),
    reload: true,
  };
}
